env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - GOFLAGS=-mod=vendor
  - GOPROXY=off
builds:
  - id: cfssl-darwin
    binary: cfssl
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    main: ./cmd/cfssl
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
  - id: cfssl-linux
    binary: cfssl
    goos:
      - linux
    goarch:
      - amd64
      - s390x
    main: ./cmd/cfssl
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=/usr/bin/musl-gcc
  - id: cfssl-linux-s390x
    binary: cfssl
    goos:
      - linux
    goarch:
      - s390x
    main: ./cmd/cfssl
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=/usr/bin/s390x-linux-gnu-gcc
      - CXX=/usr/bin/s390x-linux-gnu-g++
archives:
  - format: binary
release:
  github:
    owner: cloudflare
    name: cfssl
  prerelease: auto
changelog:
  sort: asc